image: cr.yandex/crpa15giodgbluup12vl/ci_python:latest

stages:
  - build
  - test
  - docker
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_REGISTRY_PATH: cr.yandex/crpa15giodgbluup12vl
  IMAGE_NAME: poker_backend
  IMAGE_PATH: ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}

build_py:
  stage: build
  rules:
  - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
  cache:
    paths:
      - ${PIP_CACHE_DIR}
  before_script:
    - source ~/.profile
    - git config --global --add safe.directory $CI_PROJECT_DIR
  script:
    - python3 ./build_version.py
    - python3 -m build --wheel .
  artifacts:
    paths:
      - dist/

test_py:
  stage: test
  rules:
  - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
  needs:
    - build_py
  cache:
    paths:
      - ${PIP_CACHE_DIR}
  services:
    - postgres:15.2
  variables:
    POSTGRES_PASSWORD: password
    RAVVI_POKER_DB_HOST: postgres
    RAVVI_POKER_DB_PORT: 5432
    RAVVI_POKER_DB_USER: postgres
    RAVVI_POKER_DB_PASSWORD: ${POSTGRES_PASSWORD}
    RAVVI_POKER_DB_NAME: test_ci
  before_script:
    - source ~/.profile
  script:
    - pip3 install -f ./dist ravvi-poker[tests]
    - cd tests/
    # init database
    - coverage erase
    - coverage run --append ~/.local/bin/ravvi_poker_db create ${RAVVI_POKER_DB_NAME}
    # deploy db changes
    - coverage run --append ~/.local/bin/ravvi_poker_db deploy ${RAVVI_POKER_DB_NAME}
    # run tests
    - coverage run --append -m pytest --junitxml=tests.xml .
    # coverage info
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: tests/tests.xml
      coverage_report:
        coverage_format: cobertura
        path: tests/coverage.xml

docker_build:
  stage: docker
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  needs:
    - build_py
    - test_py
  image: docker:23.0.3
  services:
    - name: docker:23.0.3-dind
  script:
    # build
    - docker build -t ${IMAGE_PATH}:${CI_COMMIT_REF_SLUG} .
    # push
    - docker push ${IMAGE_PATH}:${CI_COMMIT_REF_SLUG}
    # cleanup
    - docker image rmi ${IMAGE_PATH}:${CI_COMMIT_REF_SLUG}

deploy_develop:
  stage: deploy
  environment: develop
  rules:
  - if: $CI_COMMIT_BRANCH == 'develop'
    when: manual
  needs:
    - build_py
    - test_py
  tags:
    - develop
    - backend
    - shell
  before_script:
    - source ~/.profile
  script:
    # stop service
    - ravvi_poker_service stop
    # dump current version databse
    - ravvi_poker_db_dump
    # uninstall current version
    - pip3 uninstall -y ravvi-poker
    # install new version
    - pip3 install --user -f ./dist ravvi-poker
    # save installed packages versions
    - pip3 freeze --user >pip_freeze.txt
    # reset (drop/re-create) database
    - ravvi_poker_db_reset
    # start service
    - ravvi_poker_service start
  artifacts:
    paths:
      - pip_freeze.txt
  

deploy_staging:
  stage: deploy
  environment: staging
  rules:
  - if: $CI_COMMIT_TAG
    when: manual
  needs:
    - build_py
    - test_py
  tags:
    - poker-st1
    - shell
  before_script:
    - source ~/.profile
  script:
    # stop service
    - ravvi_poker_service stop
    # dump current version databse
    - ravvi_poker_db_dump
    # uninstall current version
    - pip3 uninstall -y ravvi-poker
    # install new version
    - pip3 install --user -f ./dist ravvi-poker
    # save installed packages versions
    - pip3 freeze --user >pip_freeze.txt
    # reset (drop/re-create) database
    - ravvi_poker_db_reset
    # start service
    - ravvi_poker_service start
  artifacts:
    paths:
      - pip_freeze.txt
