ALTER TABLE ONLY club_profile ALTER COLUMN created_ts SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE ONLY user_account ALTER COLUMN created_ts SET DATA TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE ONLY club_profile ADD COLUMN timezone TEXT;
ALTER TABLE ONLY game_player ADD COLUMN result_abs DECIMAL, ADD COLUMN result_bb DECIMAL;